version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: sh ./wait-for postgres:${DB_PORT} -- ./docker-entrypoint.sh
    env_file:
      - .env
    environment:
      - IS_CONTAINER=yes
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
